[tool.poetry]
name = "pp888"
version = "0.1.0"
description = ""
authors = ["alexdekunov <wresda@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
